[package]
name = "anonyverif"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.4", features = ["x86_64"] }
rand = "0.8.5"
aligned-vec = "0.5.0"
concrete-fft = "0.4.1"
ppverif_fhe = { git = "https://github.com/Fainabi/ppverif_fhe", rev = "48c8a7c8016788d83cf1f0551e4663c3d3f54e32" }
nalgebra = "0.33.2"

[features]
verbose = []

[[example]]
name = "demo"
path = "examples/demo.rs"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "verif"
harness = false

[[bench]]
name = "matmul"
harness = false

[[bench]]
name = "block"
harness = false
